---
# tasks file for sa-php-fpm
- name: Include PHP version switching tasks
  ansible.builtin.import_tasks: php_switchversion.yml

- name: Include PHP-FPM version specific tasks
  ansible.builtin.include_tasks: "phpfpm{{ php_version }}/main.yml"

- name: Include Xdebug tasks if enabled
  ansible.builtin.include_tasks: tasks_xdebug.yml
  when: option_install_xdebug

- name: Include additional PHP extensions
  ansible.builtin.include_tasks: php_additional_extensions.yml

- name: Include Composer tasks if enabled
  ansible.builtin.include_tasks: tasks_composer.yml
  when: option_install_composer
