  - name: PHP | Fix php family prefix for 8.4
    ansible.builtin.set_fact:
      php_version: "8.4"
      php_module_prefix: "php8.4"
      php_fpm_prefix: "php8.4"
    when: php_family == "default" or php_family == "8.4" or php_family == 8.4
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 8.3
    ansible.builtin.set_fact:
      php_version: "8.3"
      php_module_prefix: "php8.3"
      php_fpm_prefix: "php8.3"
    when: php_family == "8.3" or php_family == 8.3
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 8.2
    ansible.builtin.set_fact:
      php_version: "8.2"
      php_module_prefix: "php8.2"
      php_fpm_prefix: "php8.2"
    when: php_family == "8.2" or php_family == 8.2
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 8.1
    ansible.builtin.set_fact:
      php_version: "8.1"
      php_module_prefix: "php8.1"
      php_fpm_prefix: "php8.1"
    when: php_family == "8.1" or php_family == 8.1
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 8.0
    ansible.builtin.set_fact:
      php_version: "8.0"
      php_module_prefix: "php8.0"
      php_fpm_prefix: "php8.0"
    when: php_family == "8.0" or php_family == 8.0
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.3
    ansible.builtin.set_fact:
      php_version: "7.3"
      php_module_prefix: "php7.3"
      php_fpm_prefix: "php7.3"
    when: php_family == "7.3" or php_family == 7.3
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.2
    ansible.builtin.set_fact:
      php_version: "7.2"
      php_module_prefix: "php7.2"
      php_fpm_prefix: "php7.2"
    when: php_family == "7.2" or php_family == 7.2
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.1
    ansible.builtin.set_fact:
      php_version: "7.1"
      php_module_prefix: "php7.1"
      php_fpm_prefix: "php7.1"
    when: php_family == "7.1" or php_family == 7.1
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.0
    ansible.builtin.set_fact:
      php_version: "7.0"
      php_module_prefix: "php7.0"
      php_fpm_prefix: "php7.0"
    when: php_family == "7.0" or php_family == 7  or (php_family == "default" and ansible_distribution_release in ["xenial"])
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 5.6
    ansible.builtin.set_fact:
      php_version: "5.6"
      php_module_prefix: "php5.6"
      php_fpm_prefix: "php5.6"
    when: php_family == "5.6" or php_family == 5.6 or (php_family == "default" and ansible_distribution_release in ["trusty"])

  - name: PHP | Fix php family prefix for hvvm
    ansible.builtin.set_fact:
      php_version: hhvm
    when: php_family == "hhvm"

  - name: PHP | Add ppa ondrej/php apt repository for php 7 and 8
    ansible.builtin.apt_repository:
      repo: 'ppa:ondrej/php'
    when: php_family in [7, 7.0, "7", "7.0", 7.1, "7.1", 7.2, "7.2", 7.3, "7.3", 8, 8.0, "8.0", 8.1, "8.1", 8.2, "8.2", 8.3, "8.3", 8.4, "8.4"]
    become: true
    tags:
      -php
      -setup

  - name: PHP | Add apt repository for php 5.6
    ansible.builtin.apt_repository:
      repo: 'ppa:ondrej/php'
    when: php_family == "5.6" or php_family == 5.6 or (php_family == "default" and ansible_distribution_release in ["trusty"])
    become: true
    tags:
      -php
      -setup

  - name: PHP | Default platform provided repository is used
    ansible.builtin.debug:
      msg: "Default platform available debs will be used for php."
    when: (php_family is not defined) or (php_family == "default")
