---
  - name: Create demo site folder
    ansible.builtin.file: path="/var/www/demo56" state="directory"
    become: true

  - name: Push demo site contents
    synchronize: src="{{root_dir}}/files/demosite/" dest="/var/www/demo56"
    become: true

  - name: Template demosite nginx config
    ansible.builtin.template: src="{{root_dir}}/templates/nginx/site56.conf.j2" dest="/etc/nginx/sites-enabled/site56.conf"
    dest: /var/www/demo56
    become: true

  - name: Restart nginx
    ansible.builtin.service: name="nginx" state="restarted"
    become: true
