---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: auto

  pre_tasks:
    - name: Debug role_under_test variable
      ansible.builtin.debug:
        var: role_under_test
    - name: Debug ansible_os_family variable
      ansible.builtin.debug:
        var: ansible_os_family

    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: false
        update_cache: true
        cache_valid_time: 86400 # One day
      when: ansible_os_family == "Debian"

    - name: Install default ubuntu packages
      ansible.builtin.apt:
        name:
          - gnupg-agent
          - apt-transport-https
        state: present
      failed_when: false
      when: ansible_os_family == "Debian"

#  roles:
#    - {
#        role: "{{ role_under_test | default('role_under_test') }}",
#        firewall_used: docker,
#        docker_test: true,
#        preferred_python_version: "3"
#      }
  tasks:
    - name: Apply role runtime
      ansible.builtin.include_role:
        name: "{{ role_under_test | default('role_under_test') }}"
      vars:
        firewall_used: docker
        docker_test: true
        preferred_python_version: "3"
